import { Noto_Sans, Noto_Sans_Mono, Noto_Serif } from 'next/font/google'
import { linguiConfig } from '~/i18n/config'
import { Providers } from '~/providers'
import type { Metadata } from 'next'
import type { SupportedLocale } from '~/shared'

export function generateStaticParams() {
  return linguiConfig.locales.map((locale) => ({ locale }))
}

export const metadata: Metadata = {
  metadataBase: new URL('https://starter-next-app-two.vercel.app/'),
  title: 'Create Next App',
  description: 'Generated by create next app',
  appleWebApp: {
    title: 'Starter Next App',
  },
  icons: [
    {
      rel: 'icon',
      type: 'image/png',
      sizes: '96x96',
      url: '/favicon-96x96.png',
    },
    {
      rel: 'icon',
      type: 'image/svg+xml',
      url: '/favicon.svg',
    },
    {
      rel: 'shortcut icon',
      url: '/favicon.ico',
    },
    {
      rel: 'app-touch-icon',
      sizes: '180x180',
      url: '/apple-touch-icon.png',
    },
  ],
  openGraph: {
    title: 'Starter Next App',
    description: 'Generated by create next app',
    siteName: 'Starter Next App',
    images: [{ url: '/og.png' }],
  },
}

const fontNotoSans = Noto_Sans({
  subsets: ['latin'],
  variable: '--font-noto-sans',
  weight: ['500', '600', '700'],
})

const fontNotoSansMono = Noto_Sans_Mono({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-noto-sans-mono',
})

const fontNotoSerif = Noto_Serif({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-noto-serif',
})

export default async function Layout({
  children,
  params,
}: LayoutProps<'/[locale]'>) {
  const { locale } = (await params) as { locale: SupportedLocale }

  return (
    <html
      lang={locale}
      className={cn(
        fontNotoSans.variable,
        fontNotoSansMono.variable,
        fontNotoSerif.variable,
      )}
      suppressHydrationWarning
    >
      <body>
        <Providers locale={locale}>{children}</Providers>
      </body>
    </html>
  )
}
